// Do not edit. This file is machine generated by the Resource DLL Wizard.

library bus_prerelease;

{ITE} {DFMFileType} {Unit1.dfm}
{ITE} {DFMFileType} {Unit2.dfm}
{ITE} {DFMFileType} {Unit3.dfm}
{ITE} {DFMFileType} {Unit4.dfm}
{ITE} {DFMFileType} {Unit5.dfm}
{ITE} {DFMFileType} {Unit6.dfm}
{ITE} {DFMFileType} {Unit7.dfm}
{ITE} {RCFileType} {Win32\Debug\bus_prerelease_DRC.rc}

{$R 'Unit1.dfm' 'Form1:TForm'}
{$R 'Unit2.dfm' 'Form2:TForm'}
{$R 'Unit3.dfm' 'Form3:TForm'}
{$R 'Unit4.dfm' 'Form4:TForm'}
{$R 'Unit5.dfm' 'Form5:TForm'}
{$R 'Unit6.dfm' 'Form6:TForm'}
{$R 'Unit7.dfm' 'Form7:TForm'}
{$R 'Win32\Debug\bus_prerelease_DRC.res' 'Win32\Debug\bus_prerelease_DRC.rc'}

{$E ENU}

begin
end.
